apiVersion: apps/v1
kind: Deployment
metadata:
  name: boardgame-app
  labels:
    app: boardgame
spec:
  replicas: 2
  selector:
    matchLabels:
      app: boardgame
  template:
    metadata:
      labels:
        app: boardgame
    spec:
      containers:
      - name: boardgame
        image: 805187822135.dkr.ecr.us-east-1.amazonaws.com/devops_workshop/boardgame:latest
        ports:
        - containerPort: 8001
        imagePullPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: boardgame-service
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: "nlb"
    service.beta.kubernetes.io/aws-load-balancer-scheme: "internet-facing"
spec:
  selector:
    app: boardgame
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080
  type: LoadBalancer

